### ISSUE TITLE
Pretty print parse output

### ISSUE THREAD

**Issue by carymrobbins** [pganalyze/queryparser#2]
Is there a way to render parse trees as SQL?  I'm assuming the `queryparser` tool doesn't do this already, but maybe you could point in the direction to accomplish this.

**Comment by lfittl** [comment]
@carymrobbins Not sure I understand how you mean "render as SQL" - what exactly are you trying to accomplish?

This is the oldest of a set of libraries/tools, the current work is mostly in https://github.com/lfittl/libpg_query (C library) and https://github.com/lfittl/pg_query (Ruby library)

Unless you need a standalone binary, I'd recommend getting started with the Ruby Library, thats easiest to play around with.

Thanks in any case for being interested, hope (parts of) this work can be useful for you :)

**Comment by carymrobbins** [comment]
Thanks @lfittl.  I basically want to be able to modify the AST and then print the result as rendered SQL instead of writing all of the pretty printing logic myself.

The standalone binary or C bindings would probably work better for me since I won't be using Ruby.

**Comment by lfittl** [comment]
@carymrobbins Ah, gotcha :)

So if I understand correctly you're looking to `deparse` the modified AST tree into valid SQL again?

There's currently two ways to do this with this set of libraries:
- Use the Ruby library, which has deparse support (See https://github.com/lfittl/pg_query#modifying-a-parsed-query-and-turning-it-into-sql-again and https://github.com/lfittl/pg_query/blob/master/lib/pg_query/deparse.rb)
- Use the node.js library by @zhm at https://github.com/zhm/pg-query-parser (See https://github.com/zhm/pg-query-parser/blob/master/src/deparser.coffee)

Assuming you are neither on node.js nor on Ruby, which language are you looking to target?

I'm currently working on extracting the deparsing rules, mostly with intent to support the Go port (https://github.com/lfittl/pg_query.go), but the goal here would be that its easy to use for other languages too (even just C, possibly).

Also note that the PostgreSQL server itself has some deparsing built-in, which is not used in these libraries but might be useful if you're looking at a pure C approach to the problem.

**Comment by carymrobbins** [comment]
I'll be using Scala and/or Haskell.  I might even be able to get around the pretty printing, but was curious if it was already implemented.

Thanks for the help!

**Comment by lfittl** [comment]
@carymrobbins Nice - I think the easiest way for Scala/Haskell might be to just write the deparsing part yourself - I'll update the [libpg_query](https://github.com/lfittl/libpg_query) repository once there is a generic deparsing approach.

AFAIK @zhm approached the problem by using Postgres' own regression test files (https://github.com/postgres/postgres/tree/master/src/test/regress/sql) for testing, parsing them into the AST, then deparsing the AST, and parsing the deparsed SQL again and comparing that AST with the original.

Thats probably the fastest way to get reasonably complete support. Let me know if you publish something as a library, happy to link to it :)

**Comment by carymrobbins** [comment]
Sounds great, thanks @lfittl!
